### ISSUE TITLE
ZoeDepth

### ISSUE THREAD

**Issue by shkarupa-alex** [YuiNsky/Multi-resolution-Monocular-Depth-Map-Fusion-by-Self-supervised-Gradient-based-Composition#3]
It would be cool if you add latest SOTA https://github.com/isl-org/ZoeDepth to this repo.
I've tried to it myself, but failed to run ZoeDepth with different resolutions (it seems that image always resized to the same size somewhere inside model)

**Comment by YuiNsky** [comment]
Thanks for the question. It seems they use MLP in their Metric Bins Module, so the input size of the image cannot be changed directly to apply our method.
