### ISSUE TITLE
Does the model overfit in your dataset?

### ISSUE THREAD

**Issue by javierztl** [YuiNsky/Multi-resolution-Monocular-Depth-Map-Fusion-by-Self-supervised-Gradient-based-Composition#4]
I tried my picture, the edge around the person has some glow, and the detail did not perform as expected. 

![LeRes50_0](https://user-images.githubusercontent.com/43167789/227410602-d3b82c3e-8b64-4ea3-ab0c-56f1a96d4342.jpg)

**Comment by YuiNsky** [comment]
Thanks for your question. As we mentioned in our paper, depth estimation on high resolution will not work so great when facing a difficult situation. The background of this picture lacks features and is too bright. And this glow problem may also happen when the original resolution of the image is not big enough. You can check these and try another input.
